# Generated by Django 4.1 on 2023-10-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_delivery', models.CharField(default=1, max_length=200, verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Тип Доставки',
                'verbose_name_plural': 'Типы доставки',
                'ordering': ['type_delivery'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адреса доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['street'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ul', models.CharField(help_text='Форма собственности и название', max_length=70, verbose_name='Имя юр. лица')),
                ('address_ur', models.TextField(blank=True, help_text='Полный почтовый адрес', null=True, verbose_name='Юр. Адрес')),
                ('address_post', models.TextField(blank=True, null=True, verbose_name='Почтовый Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Телефон резервный')),
                ('email', models.EmailField(blank=True, max_length=20, verbose_name='Электронная почта')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=12, verbose_name='ОКПО')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name_ul'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильный телефон')),
                ('telegram', models.CharField(blank=True, max_length=15, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organisation')),
            ],
        ),
    ]
