# Generated by Django 5.0.6 on 2024-06-04 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_method',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.delivery', verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='flat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира/офис'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='house',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ЗАКАЗЧИК!!'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(default=2, max_length=200, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_ul',
            field=models.CharField(default='Физ. лицо', help_text='Форма собственности и название.Если платильщик физ. Лицо, оаставить физ. лицо. ', max_length=70, verbose_name='Имя юр. лица'),
        ),
    ]
