# Generated by Django 4.1 on 2023-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(default=2, max_length=200, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name_ul',
            field=models.CharField(default='Физ. лицо', help_text='Форма собственности и название.Если платильщик физ. Лицо, оаставить физ. лицо. ', max_length=70, verbose_name='Имя юр. лица'),
        ),
    ]
