# Generated by Django 5.0.6 on 2025-02-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(default=1, max_length=200, verbose_name='Тип доставки'),
        ),
    ]
