# Generated by Django 4.1 on 2023-12-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_deliveryaddress_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="account.delivery",
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="district",
            field=models.CharField(default=1, max_length=100, verbose_name="Регион"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="region",
            field=models.CharField(default=1, max_length=100, verbose_name="Область"),
            preserve_default=False,
        ),
    ]
