# Generated by Django 4.1 on 2023-12-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_deliveryaddress_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="account.delivery",
                verbose_name="Тип доставки",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Регион"
            ),
        ),
    ]
