# Generated by Django 5.0.6 on 2024-12-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_delivery', models.CharField(default=2, max_length=200, verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Тип Доставки',
                'verbose_name_plural': 'Типы доставки',
                'ordering': ['type_delivery'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(help_text='Форма собственности и название', max_length=200, verbose_name='Имя юр. лица')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('address', models.CharField(help_text='Полный почтовый адрес', max_length=256, verbose_name='Юр. Адрес')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название Банка')),
                ('bik_bank', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК Банка')),
                ('bankCorrAccount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Кор.счет')),
                ('address_post', models.CharField(blank=True, max_length=256, null=True, verbose_name='Почтовый Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=40, verbose_name='Электронная почта')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name_full'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дом')),
                ('entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Этаж')),
                ('flat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира/офис')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('delivery_method', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.delivery', verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Адреса доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['street'],
            },
        ),
    ]
