# Generated by Django 5.0.6 on 2025-01-31 13:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CUSTOMER_RETAIL', 'Клиент'), ('CUSTOMER_AGENCY', 'Рекламное агентство'), ('MANAGER', 'Менеджер'), ('OPERATOR', 'Оператор'), ('FINANCIER', 'Бухгалтер'), ('AnonymousUser', 'Незарегистрированный'), ('COURIER', 'Курьер')], default='CUSTOMER_RETAIL', max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('email_verify', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='В формате +7 953 119-33-67', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(default=False, help_text='Установите Да если к номеру телефона подключен Whatsapp', verbose_name='Присылать уведомления на Whatsapp')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/')),
                ('telegram', models.BooleanField(blank=True, help_text='Установите Да если к номеру телефона подключен Telegram', null=True, verbose_name='Присылать уведомления в Telegram')),
                ('lid_status', models.CharField(choices=[('ANSWER', 'ответил на вопросы'), ('POSTING', 'выслал дополнительную информацию'), ('DESIGN_HOW', 'Отослал дизайнер для расчета'), ('DESIGN', 'Разработка макета'), ('ORDER', 'Выставление счета'), ('PRODUCTION', 'В работе'), ('COMPLETE', 'Cообщили о готовности'), ('FEEDBACK', 'Отсылаем просьбу об отзыве')], default='ANSWER', max_length=64, verbose_name='Статус лида')),
                ('interest_text', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелиц лида')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('interest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.interest', verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
