# Generated by Django 5.0.6 on 2025-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lid_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_creation',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
