version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_django
    volumes:
      - ~/.pg/pg_data/django:/var/lib/postgresql/data
    env_file:
      - .env

    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: sasha
      POSTGRES_DB: db01
      PGDATA: /home/sasha/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"

    ports:
      - "54321:5432"

