version: '3.9'

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    volumes:
      - ~/.pg/pg_data/django:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  django_project:
    build:
      dockerfile: Dockerfile
      context: .
    image: django_docker:latest
    container_name: django_docker
    depends_on:
      - postgres_db
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 mysite.wsgi:application"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_for_django
    image: nginx_for_django
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - postgres_db
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
volumes:
  static_volume:
  media_volume: