version: '3.9'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - ~/.pg/pg_data/django:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  django_project:
    build:
      dockerfile: Dockerfile
      context: .
    image: django_docker:latest
    container_name: django_docker
    depends_on:
      - postgres_db
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate  && ./manage.py add_test_data && ./manage.py add_price && gunicorn -b 0.0.0.0:8000 mysite.wsgi:application"
    restart: always

  worker:
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - django_project
    command: 'celery -A mysite worker -l info'

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_for_django
    image: nginx_for_django
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - postgres_db
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    restart: always
volumes:
  static_volume:
  media_volume: