version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres_django
    volumes:
      - ~/.pg/pg_data/django:/var/lib/postgresql/data
    env_file:
      - .env
  DjangoProject:
    build:
      dockerfile: Dockerfile
      context: .
    image: django_docker:latest
    container_name: django_docker
    depends_on:
      - db
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 mysite.wsgi:application"










    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: sasha
      POSTGRES_DB: db01
      PGDATA: /home/sasha/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"

    ports:
      - "54321:5432"

