version: '2'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - ~/.pg/pg_data/django:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
  django_project:
    build:
      dockerfile: Dockerfile
      context: .
    image: django_docker:latest
    container_name: django_docker
    depends_on:
      - postgres_db
    volumes:
        static_volume:
          driver_opts:
            type: none
            device: /data/django_static  # Путь на хосте
            o: bind
      - media_volume:/django/media
    env_file:
      - .env
    ports:
      - 8000:8000

    command: >
      bash -c "python manage.py makemigrations &&
                   python manage.py migrate &&
                   python manage.py add_price &&
                   python manage.py collectstatic --noinput &&
                   gunicorn -b 0.0.0.0:8000 mysite.wsgi:application"

    restart: always

  worker:
    restart: always
    build: .
    volumes:
      - /:/app
      - static_volume:
          driver_opts:
            type: none
            device: /data/django_static  # Путь на хосте
            o: bind
      - media_volume:/django/media
    depends_on:
      - redis
      - django_project
    command: 'celery -A mysite worker -l info'

  celery-beat:
    restart: always
    build: .
    volumes:
      - /:/app
      - static_volume:
          driver_opts:
            type: none
            device: /data/django_static  # Путь на хосте
            o: bind
      - media_volume:/django/media
    depends_on:
      - redis
      - django_project
    command: 'celery -A mysite beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler'

  flower:
    container_name: flower
    build: .
    ports:
      - 5555:5555
    volumes:
      - /:/app
      - static_volume:
          driver_opts:
            type: none
            device: /data/django_static  # Путь на хосте
            o: bind
      - media_volume:/django/media
    depends_on:
      - redis
    command: 'celery -A mysite flower'

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_for_django
    image: nginx_for_django
    volumes:
      - static_volume:
          driver_opts:
            type: none
            device: /data/django_static  # Путь на хосте
            o: bind
      - media_volume:/django/media
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

    depends_on:
      - django_project
      - postgres_db
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"

    restart: always

volumes:
  static_volume:
  media_volume:
  vhost:
  html:
