# Generated by Django 5.2.3 on 2025-06-23 21:13

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Интерес')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='Lids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lid_status', models.CharField(choices=[('ANSWER', 'Ответил на вопросы'), ('REQUEST', 'Неотвеченный запрос'), ('POSTING', 'Выслал дополнительную информацию'), ('DESIGN_HOW', 'Отослал дизайнеру для расчета'), ('DESIGN', 'Разработка макета'), ('ORDER', 'Выставление счета'), ('PRODUCTION', 'В работе'), ('COMPLETE', 'Cообщили о готовности'), ('FEEDBACK', 'Отсылаем просьбу об отзыве'), ('CLOSED', 'Закрыт')], default='REQUEST', max_length=64, verbose_name='Статус лида')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='В формате +7 953 119-33-67', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'whatsapp'), ('TELEGRAM', 'telegram'), ('EMAIL', 'email'), ('PHONE', 'Телефонный звонок'), ('SITE', 'Сайт')], default='SITE', max_length=64, verbose_name='Канал продаж')),
                ('interest_text', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('interest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lids.interest', verbose_name='Тема сообщения')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
