# Generated by Django 5.0.6 on 2025-01-22 13:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Интерес')),
            ],
        ),
        migrations.CreateModel(
            name='Lids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(auto_created='Email', max_length=254)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='В формате +7 953 119-33-67', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'whatsapp'), ('TELEGRAM', 'telegram'), ('EMAIL', 'email'), ('PHONE', 'Телефонный звонок')], default='PHONE', max_length=64, verbose_name='Канал продаж')),
                ('interest_text', models.TextField(verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lids.interest', verbose_name='Интерес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелиц лида')),
            ],
        ),
    ]
