# Generated by Django 5.0.6 on 2025-02-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterModelOptions(
            name='lids',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
        migrations.AddField(
            model_name='lids',
            name='lid_status',
            field=models.CharField(choices=[('ANSWER', 'ответил на вопросы'), ('POSTING', 'выслал дополнительную информацию'), ('DESIGN_HOW', 'Отослал дизайнер для расчета'), ('DESIGN', 'Разработка макета'), ('ORDER', 'Выставление счета'), ('PRODUCTION', 'В работе'), ('COMPLETE', 'Cообщили о готовности'), ('FEEDBACK', 'Отсылаем просьбу об отзыве')], default='ANSWER', max_length=64, verbose_name='Статус лида'),
        ),
        migrations.AlterField(
            model_name='lids',
            name='email',
            field=models.EmailField(auto_created='Email', blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lids',
            name='interest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lids.interest', verbose_name='Интерес'),
        ),
        migrations.AlterField(
            model_name='lids',
            name='interest_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='lids',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелиц лида'),
        ),
    ]
