# Generated by Django 5.0.6 on 2025-02-14 16:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='В формате +7 953 119-33-67', max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('size_banner', models.CharField(blank=True, help_text='ширина Х высота в метрах', max_length=255, null=True, verbose_name='Размер носителя')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.material', verbose_name='Материал для печати')),
            ],
        ),
    ]
