# Generated by Django 5.0.6 on 2025-02-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDeliveryBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('img_production', models.ImageField(upload_to='img_production/%Y/%m/%d/', verbose_name='Фото продукции в автобусе')),
                ('img_phone', models.ImageField(upload_to='img_phone/%Y/%m/%d/', verbose_name='Фото телефона водителя')),
                ('img_bus', models.ImageField(upload_to='img_bus/%Y/%m/%d/', verbose_name='Фото номера автобуса')),
                ('comments', models.TextField(default='Набрать в 2-00', verbose_name='Комментарии')),
            ],
        ),
    ]
