# Generated by Django 5.0.6 on 2025-02-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('description', models.CharField(max_length=200, verbose_name='Описание направления деятельности')),
                ('email_contractor', models.EmailField(max_length=254, verbose_name='Email организации для приема заказов')),
                ('phone_contractor', models.CharField(max_length=11, verbose_name='Телефон организации')),
                ('phone_contractor_2', models.CharField(max_length=11, verbose_name='Телефон whatsapp')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='Отсылать уведомления на Whatsapp')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('contact_contractor', models.CharField(max_length=23, verbose_name='Контактное лицо')),
                ('time_work_order', models.CharField(default='24', max_length=24, verbose_name='Время обработки заказов в часах')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255, verbose_name='Финишная обработка')),
                ('price_contractor', models.FloatField(blank=True, default=None, help_text='Цена за 1 м. погонный', max_length=100, null=True, verbose_name='Себестоимость работы в руб.')),
                ('price', models.FloatField(help_text='Цена за 1 м. погонный', max_length=100, verbose_name='Стоимость работы в руб.')),
                ('price_customer_retail', models.FloatField(blank=True, help_text='Цена за 1 м. погонный', max_length=100, null=True, verbose_name='Стоимость работы розница в руб.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Финишная обработка',
                'verbose_name_plural': 'Финишные обработки',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='Введите имя материала для печати', max_length=100, null=True, verbose_name='Материал для печати')),
                ('price_contractor', models.FloatField(blank=True, default=None, help_text='За 1 м2', max_length=100, null=True, verbose_name='Себестоимость печати в руб.')),
                ('price', models.FloatField(help_text='За 1 м2', max_length=100, verbose_name='Стоимость печати для РА в руб.')),
                ('price_customer_retail', models.FloatField(blank=True, help_text='За 1 м2', max_length=100, null=True, verbose_name='Стоимость печати розница в руб.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный ')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы для печати',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64, verbose_name='Статус файла')),
            ],
            options={
                'verbose_name': 'Статус файла',
                'verbose_name_plural': 'Статусы файлов',
            },
        ),
        migrations.CreateModel(
            name='TypePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_print', models.CharField(max_length=128, verbose_name='Метод печати')),
                ('info_type_print', models.TextField(verbose_name='Описание метода печати')),
            ],
            options={
                'verbose_name': 'Тип печати',
                'verbose_name_plural': 'Типы печати',
                'ordering': ['type_print'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('width', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Ширина')),
                ('length', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Длина')),
                ('resolution', models.IntegerField(default=0, help_text='для баннера72 dpi, для Пленки 150 dpi', verbose_name='Разрешение')),
                ('color_model', models.CharField(default='CMYK', help_text='Для корректной печати модель должна быть CMYK', max_length=10, verbose_name='Цветовая модель')),
                ('size', models.FloatField(default=0, verbose_name='Размер в Мб')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('images', models.ImageField(upload_to='image', verbose_name='Загрузка файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарии к файлу')),
                ('FinishWork', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.finishwork', verbose_name='Финишная обработка')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.material', verbose_name='Материал')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ЗАКАЗЧИК!!')),
                ('status_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.statusproduct', verbose_name='Статус файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='type_print',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.typeprint', verbose_name='Тип печати'),
        ),
        migrations.CreateModel(
            name='UseCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('width', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Ширина')),
                ('length', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Длина')),
                ('results', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('FinishWork', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.finishwork', verbose_name='Финишная обработка')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.material', verbose_name='Материал')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Расчет клиентов сайта',
                'verbose_name_plural': 'Расчеты клиентов сайта',
            },
        ),
    ]
