# Generated by Django 4.1 on 2023-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Поставщик продукции')),
            ],
            options={
                'verbose_name': 'Подрядчикии',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(max_length=255, verbose_name='Поля вокруг изображения')),
            ],
            options={
                'verbose_name': 'Поле вокруг печати',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='FinishWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255, verbose_name='Финишная обработка')),
                ('price_contractor', models.FloatField(blank=True, default=None, help_text='Цена за 1 м. погонный', max_length=100, null=True, verbose_name='Себестоимость работы в руб.')),
                ('price', models.FloatField(help_text='Цена за 1 м. погонный', max_length=100, verbose_name='Стоимость работы в руб.')),
                ('price_customer_retail', models.FloatField(blank=True, help_text='Цена за 1 м. погонный', max_length=100, null=True, verbose_name='Стоимость работы розница в руб.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Финишная обработка',
                'verbose_name_plural': 'Финишные обработки',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='Введите имя материала для печати', max_length=100, null=True, verbose_name='Материал для печати')),
                ('price_contractor', models.FloatField(blank=True, default=None, help_text='За 1 м2', max_length=100, null=True, verbose_name='Себестоимость печати в руб.')),
                ('price', models.FloatField(help_text='За 1 м2', max_length=100, verbose_name='Стоимость печати для РА в руб.')),
                ('price_customer_retail', models.FloatField(blank=True, help_text='За 1 м2', max_length=100, null=True, verbose_name='Стоимость печати розница в руб.')),
                ('resolution_print', models.IntegerField(blank=True, default=None, help_text='разрешение для печати на материале', null=True, verbose_name='DPI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный ')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы для печати',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('width', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Ширина')),
                ('length', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Длина')),
                ('resolution', models.IntegerField(default=0, help_text='для баннера 72 dpi, для Пленки 150 dpi', verbose_name='Разрешение')),
                ('color_model', models.CharField(default='CMYK', help_text='Для корректной печати модель должна быть CMYK', max_length=10, verbose_name='Цветовая модель')),
                ('size', models.FloatField(default=0, verbose_name='Размер в Мб')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('images', models.FileField(upload_to='image', verbose_name='Загрузка файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('in_order', models.BooleanField(blank=True, default=0, null=True, verbose_name='Позиция в заказе')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64, verbose_name='Статус файла')),
            ],
            options={
                'verbose_name': 'Статус файла',
                'verbose_name_plural': 'Статусы файлов',
            },
        ),
        migrations.CreateModel(
            name='TypePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_print', models.CharField(max_length=128, verbose_name='Метод печати')),
                ('info_type_print', models.TextField(verbose_name='Описание метода печати')),
            ],
            options={
                'verbose_name': 'Тип печати',
                'verbose_name_plural': 'Типы печати',
                'ordering': ['type_print'],
            },
        ),
        migrations.CreateModel(
            name='UploadArh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.FileField(upload_to='upload_arhive')),
            ],
        ),
    ]
