# Generated by Django 5.2.3 on 2025-06-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='FinishWork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.finishwork', verbose_name='Финишная обработка'),
        ),
    ]
