# Generated by Django 4.1 on 2023-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_product_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadArhive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.FileField(upload_to='upload_arhive')),
            ],
        ),
        migrations.AlterModelOptions(
            name='finishwork',
            options={'verbose_name': 'Финишная обработка', 'verbose_name_plural': 'Финишные обработки'},
        ),
        migrations.AlterField(
            model_name='finishwork',
            name='price',
            field=models.FloatField(help_text='Цена за 1 м. погонный', max_length=100, verbose_name='Стоимость работы в руб.'),
        ),
        migrations.AlterField(
            model_name='finishwork',
            name='price_contractor',
            field=models.FloatField(blank=True, default=None, help_text='Цена за 1 м. погонный', max_length=100, null=True, verbose_name='Себестоимость работы в руб.'),
        ),
        migrations.AlterField(
            model_name='finishwork',
            name='work',
            field=models.CharField(max_length=255, verbose_name='Финишная обработка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='image/2023-08-12'),
        ),
    ]
