# Generated by Django 4.2.11 on 2024-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к файлу'),
        ),
    ]
