# Generated by Django 4.2.11 on 2024-05-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_product_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('width', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Ширина')),
                ('length', models.FloatField(default=0, help_text='Указывается в см.', verbose_name='Длина')),
                ('results', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('FinishWork', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.finishwork', verbose_name='Финишная обработка')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Расчет клиентов сайта',
                'verbose_name_plural': 'Расчеты клиентов сайта',
            },
        ),
    ]
