# Generated by Django 4.1 on 2023-08-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadarhive_alter_finishwork_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadArhive',
            new_name='UploadArh',
        ),
    ]
