# Generated by Django 5.0.6 on 2024-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_product_fields_alter_usecalculator_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='contact_contractor',
            field=models.CharField(default=1, max_length=23, verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='description',
            field=models.CharField(default=1, max_length=200, verbose_name='Описание направления деятельности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='email_contractor',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone_contractor',
            field=models.CharField(default=1, max_length=11, verbose_name='Телефон организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone_contractor_2',
            field=models.CharField(default=1, max_length=11, verbose_name='Телефон организации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование орнаеизации'),
        ),
    ]
