# Generated by Django 4.1 on 2023-09-13 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0006_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishwork',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный '),
        ),
        migrations.AlterField(
            model_name='material',
            name='type_print',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.typeprint', verbose_name='Тип печати'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ЗАКАЗЧИК!!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.fields', verbose_name='Поля вокруг изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='FinishWork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.finishwork', verbose_name='Финишная обработка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_model',
            field=models.CharField(default='CMYK', help_text='Для корректной печати модель должна быть CMYK', max_length=10, verbose_name='Цветовая модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='image/2023-09-13'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='files.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='files.statusproduct', verbose_name='Статус файла'),
        ),
        migrations.AlterField(
            model_name='typeprint',
            name='info_type_print',
            field=models.TextField(verbose_name='Описание метода печати'),
        ),
    ]
