# Generated by Django 5.0.6 on 2024-07-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_contractor_address_contractor_contact_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование организации'),
        ),
    ]
