# Generated by Django 4.1 on 2023-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_model',
            field=models.CharField(default='CMYK', help_text='Для корректной печати модель должна быть CMYK', max_length=10, verbose_name='Цветовая модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='image/2023-08-26'),
        ),
    ]
