# Generated by Django 4.1 on 2023-09-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_material_is_active_alter_material_type_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishwork',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный '),
        ),
    ]
