# Generated by Django 4.1 on 2023-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_finishwork_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishwork',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(upload_to='image/2023-09-11'),
        ),
    ]
