# Generated by Django 5.0.6 on 2025-05-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lids', '0002_alter_lids_channel_alter_lids_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_vars', models.CharField(max_length=60, verbose_name='Варианты сложности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость разработки')),
                ('teme', models.DateTimeField(verbose_name='Время на разработку')),
            ],
            options={
                'verbose_name_plural': 'Варианты сложности макета',
            },
        ),
        migrations.CreateModel(
            name='OrderDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('description', models.TextField(verbose_name='Дополнительные сведения')),
                ('images', models.ImageField(upload_to='images/designs', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.complexity', verbose_name='Сложность макета')),
                ('interest', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='lids.interest', verbose_name='Категория макета')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Бриф',
                'verbose_name_plural': 'Брифы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='designs.orderdesign')),
            ],
        ),
    ]
