# Generated by Django 5.2.3 on 2025-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_vars', models.CharField(max_length=60, verbose_name='Варианты сложности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость разработки')),
                ('teme', models.DateTimeField(verbose_name='Время на разработку')),
            ],
            options={
                'verbose_name_plural': 'Варианты сложности макета',
            },
        ),
        migrations.CreateModel(
            name='OrderDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название брифа')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('description', models.TextField(verbose_name='Тех.задание')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/designs', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order_status', models.CharField(choices=[('AWAITING_PAY', 'Ожидает оплаты'), ('PAY', 'Оплачен'), ('IN_WORK', 'В работе'), ('AGREED', 'УТВЕРЖДЕН'), ('CLOSED', 'Закрыт')], default='AWAITING_PAY', max_length=100, verbose_name='Статус Брифа')),
            ],
            options={
                'verbose_name': 'Бриф',
                'verbose_name_plural': 'Брифы',
                'ordering': ['title'],
            },
        ),
    ]
