# Generated by Django 5.2.3 on 2025-06-23 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('lids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='complexity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designs.complexity', verbose_name='Выберите сложность макета'),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='interest',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='lids.interest', verbose_name='Категория макета'),
        ),
        migrations.AddField(
            model_name='orderdesign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='comments',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='designs.orderdesign', verbose_name='Дизайн'),
        ),
    ]
