# Generated by Django 5.0.6 on 2025-01-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideGlassСar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст на наклейке')),
                ('width', models.IntegerField(verbose_name='Ширина в символах')),
                ('strings', models.IntegerField(verbose_name='Количество строк')),
                ('font', models.CharField(max_length=255, verbose_name='Шрифт')),
                ('size_font', models.IntegerField(verbose_name='Размер шрифта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
