# Generated by Django 5.0.6 on 2025-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_pic', models.CharField(max_length=64, verbose_name='Размер картины')),
            ],
        ),
    ]
