# Generated by Django 4.1 on 2023-06-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(verbose_name='заказ оплачен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organisation_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.organisation', verbose_name='организация платильщик')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='За 1 м2', max_length=100, verbose_name='Стоимость печати в руб.')),
                ('quantity', models.IntegerField(default=1, help_text='Введите количество', verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Ордер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.product', verbose_name='Продукт')),
            ],
        ),
    ]
