# Generated by Django 4.1 on 2023-10-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ЗАКАЗЧИК!!'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.delivery', verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='order',
            name='organisation_payer',
            field=models.ForeignKey(help_text='Выберите организацию платильщик', on_delete=django.db.models.deletion.CASCADE, to='account.organisation', verbose_name='организация платильщик'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.statusorder', verbose_name='Статус заказа'),
        ),
    ]
