# Generated by Django 5.2.3 on 2025-06-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_delivery_type_delivery'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.delivery', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cost_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Себестоимость Итого'),
        ),
    ]
