# Generated by Django 4.1 on 2023-09-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_organisation_phone2_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_total_price',
            field=models.FloatField(blank=True, help_text='Себестоимость заказа', max_length=10, null=True, verbose_name='Общая Себестоимость '),
        ),
        migrations.AddField(
            model_name='order',
            name='path_arhive',
            field=models.FileField(blank=True, null=True, upload_to='arhive/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price_per_item',
            field=models.FloatField(blank=True, help_text='За 1 шт.', max_length=100, null=True, verbose_name='Себестоимость шт.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Себестоимость шт.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organisation_payer',
            field=models.ForeignKey(help_text='Выберите организацию платильщик', on_delete=django.db.models.deletion.CASCADE, to='account.organisation', verbose_name='организация платильщик'),
        ),
    ]
