# Generated by Django 4.1 on 2023-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_total_price',
            field=models.FloatField(blank=True, help_text='Себестоимость заказа', max_length=10, null=True, verbose_name='Общая Себестоимость '),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price_per_item',
            field=models.FloatField(blank=True, help_text='За 1 шт.', max_length=100, null=True, verbose_name='Себестоимость шт.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Себестоимость шт.'),
        ),
    ]
