# Generated by Django 5.0.6 on 2024-06-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_deliveryaddress_delivery_method_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка для оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.delivery', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organisation_payer',
            field=models.ForeignKey(blank=True, help_text='Выберите организацию платильщик', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organisation', verbose_name='организация платильщик'),
        ),
    ]
