# Generated by Django 4.1 on 2023-10-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка для оплаты'),
        ),
    ]
