# Generated by Django 4.1 on 2023-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_organisation_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_arhive',
            field=models.FileField(blank=True, null=True, upload_to='arhive/<built-in function id>'),
        ),
    ]
