# Generated by Django 4.1 on 2023-10-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('orders', '0003_order_pay_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='organisation_payer',
            field=models.ForeignKey(blank=True, help_text='Выберите организацию платильщик', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.organisation', verbose_name='организация платильщик'),
        ),
    ]
