# Generated by Django 4.1 on 2023-09-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_arhive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_arhive',
            field=models.FileField(blank=True, null=True, upload_to='arhive/'),
        ),
    ]
