# Generated by Django 4.1 on 2023-11-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_delivery_type_delivery_and_more'),
        ('orders', '0004_alter_order_organisation_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.delivery', verbose_name='Доставка'),
        ),
    ]
