# Generated by Django 4.1 on 2023-10-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_order_arhive"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="orders/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_arhive",
            field=models.FileField(
                blank=True, null=True, upload_to="arhive/<built-in function id>"
            ),
        ),
    ]
